# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
#cmd = "swag init && go build -o ./tmp/main ./main.go"
cmd = "swag init -d=. --exclude=cmd/batch,cmd/ws,cmd/appinfo,cmd/gw,cmd/partner -g=cmd/api/main.go && go build -o ./tmp/api ./cmd/api"
#cmd = "swag init -d=. --exclude=cmd/batch,cmd/ws,cmd/appinfo,cmd/gw,cmd/partner -g=cmd/api/main.go && bob build api"
# Binary file yields from `cmd`.
bin = "tmp/api"
# Customize binary.
full_bin = "./tmp/api"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "mustache", "hbs", "pug", "yml", "conf", "csv"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "vendor", "node_modules", "_generate", "docs", "readme"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
