version: '3'

tasks:
  run-api:
    desc: Run Api
    watch: true
    cmds:
      - cmd: air
        platforms: [darwin]
      - cmd: air -c .air/.air.api-wd.toml
        platforms: [windows]

  clean-modcache:
    cmds:
      - go clean -modcache
      - go mod tidy

  gosec:
    cmds:
      - gosec -exclude-generated ./...

  lint-run:
    cmds:
      - golangci-lint run ./...

  lint-run-fix:
    cmds:
      - golangci-lint run --fix

  tools:
    cmds:
      - go install github.com/go-delve/delve/cmd/dlv@latest
      - go install github.com/cosmtrek/air@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install github.com/go-task/task/v3/cmd/task@latest